### ISSUE TITLE
Could not login with username, Log is fine

### ISSUE THREAD

**Issue by bitbrewDE** [shopwareLabs/SwagMediaSftp#11]
Hello Guys.

I get a strange error.

Oops! An error has occurred!
The following notes should help you.
Could not login with username: [USERNAME], host:  [HOST] in  custom/plugins/SwagMediaSftp/vendor/league/flysystem-sftp/src/SftpAdapter.php  on line 233
Stack trace: #0  custom/plugins/SwagMediaSftp/vendor/league/flysystem-sftp/src/SftpAdapter.php(195):

But the Log tells, that the adapter connects correctly:

Connection from xyz port 30662 on zzz port 22
Accepted password for USER from xzy port 30662 ssh2
User child is on pid 419902
Starting session: subsystem 'sftp' for USER from xyz port 30662 id 0
Close session: user sUSER  from xyz port 30662 id 0

Here is my config

	'cdn' => [
		'backend' => 'sftp',
		'adapters' => [
			'sftp' => [
				'type' => 'sftp',
				'mediaUrl' => 'https://images.myurl.tld',
				'host' => 'hostname.tld',
				'port' => 22,
				'username' => 'user',
				'password' => 'password',
				'root' => '/PATH-TO-SHOPWARE-ROOT/', _(is that correct, or should i use /media/ also?)_
				'timeout' => 10
			]
		]
	]

Here is the full Stack trace. It seens, that he tries to load any metadata, because he checks some pathes like "image/1b/". I tried to load a media src for basic images from the editor.
 #0 custom/plugins/SwagMediaSftp/vendor/league/flysystem-sftp/src/SftpAdapter.php(195): League\Flysystem\Sftp\SftpAdapter->login()
 #1 custom/plugins/SwagMediaSftp/vendor/league/flysystem/src/Adapter/AbstractFtpAdapter.php(563): League\Flysystem\Sftp\SftpAdapter->connect()
 #2 custom/plugins/SwagMediaSftp/vendor/league/flysystem-sftp/src/SftpAdapter.php(548): League\Flysystem\Adapter\AbstractFtpAdapter->getConnection()
 #3 custom/plugins/SwagMediaSftp/vendor/league/flysystem-sftp/src/SftpAdapter.php(540): League\Flysystem\Sftp\SftpAdapter->getMetadata('media/image/1b/...')
 #4 custom/plugins/SwagMediaSftp/vendor/league/flysystem/src/Filesystem.php(54): League\Flysystem\Sftp\SftpAdapter->has('media/image/1b/...')
 #5 engine/Shopware/Bundle/MediaBundle/MediaService.php(158): League\Flysystem\Filesystem->has('media/image/1b/...')
 #6 engine/Shopware/Controllers/Backend/MediaManager.php(222): Shopware\Bundle\MediaBundle\MediaService->has('media/image/1b/...')
 #7 engine/Library/Enlight/Controller/Action.php(192): Shopware_Controllers_Backend_MediaManager->getAlbumMediaAction()
 #8 engine/Library/Enlight/Controller/Dispatcher/Default.php(563): Enlight_Controller_Action->dispatch('getAlbumMediaAc...')
 #9 engine/Library/Enlight/Controller/Front.php(222): Enlight_Controller_Dispatcher_Default->dispatch(Object(Enlight_Controller_Request_RequestHttp), Object(Enlight_Controller_Response_ResponseHttp))
 #10 engine/Shopware/Kernel.php(202): Enlight_Controller_Front->dispatch()
 #11 vendor/symfony/http-kernel/HttpCache/SubRequestHandler.php(102): Shopware\Kernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
 #12 vendor/symfony/http-kernel/HttpCache/HttpCache.php(448): Symfony\Component\HttpKernel\HttpCache\SubRequestHandler::handle(Object(Shopware\Kernel), Object(Symfony\Component\HttpFoundation\Request), 1, true)
 #13 engine/Shopware/Components/HttpCache/AppCache.php(260): Symfony\Component\HttpKernel\HttpCache\HttpCache->forward(Object(Symfony\Component\HttpFoundation\Request), true, NULL)
 #14 vendor/symfony/http-kernel/HttpCache/HttpCache.php(238): Shopware\Components\HttpCache\AppCache->forward(Object(Symfony\Component\HttpFoundation\Request), true)
 #15 engine/Shopware/Components/HttpCache/AppCache.php(105): Symfony\Component\HttpKernel\HttpCache\HttpCache->pass(Object(Symfony\Component\HttpFoundation\Request), true)
 #16 shopware.php(122): Shopware\Components\HttpCache\AppCache->handle(Object(Symfony\Component\HttpFoundation\Request))
 #17 {main}

**Comment by bitbrewDE** [comment]
I used a private key also and it worked for me.
